# Generated by Django 5.0.3 on 2024-05-18 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations_images/')),
                ('category', models.CharField(choices=[('clothes', 'Roupa'), ('furniture', 'Móvel'), ('electronics', 'Eletrônico'), ('toy', 'Brinquedo'), ('book', 'Livro')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('used_good', 'Usado - Bom'), ('used_acceptable', 'Usado - Aceitável')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade_entrega', models.IntegerField(choices=[(1, '1 Estrelas'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], verbose_name='Disponibilidade de Entrega/Retirada')),
                ('condicao_item', models.IntegerField(choices=[(1, '1 Estrelas'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], verbose_name='Condição do Item')),
                ('higiene_item', models.IntegerField(choices=[(1, '1 Estrelas'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], verbose_name='Higiene do Item')),
                ('adequacao_descricao', models.IntegerField(choices=[(1, '1 Estrelas'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], verbose_name='Adequação à Descrição')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('doacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='main.doacao')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('hora_agendamento', models.TimeField(verbose_name='Hora do Agendamento')),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doacao', verbose_name='Doação Relacionada')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcados_como_favorito', to='main.doacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='main.doacao')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
