# Generated by Django 5.0.3 on 2024-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations_images/')),
                ('category', models.CharField(choices=[('clothes', 'Roupas'), ('furniture', 'Móveis'), ('electronics', 'Eletrônicos'), ('toys', 'Brinquedos'), ('books', 'Livros')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('used', 'Usado'), ('worn', 'Desgastado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('clothes', 'Roupa'), ('furniture', 'Móvel'), ('electronics', 'Eletrônico'), ('toy', 'Brinquedo'), ('book', 'Livro')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('used_good', 'Usado - Bom'), ('used_acceptable', 'Usado - Aceitável')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
