# Generated by Django 5.0.3 on 2024-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='condition',
            field=models.CharField(choices=[('new', 'Novo'), ('used_good', 'Usado - Bom'), ('used_acceptable', 'Usado - Aceitável')], max_length=50),
        ),
    ]
